apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-crud
  template:
    metadata:
      labels:
        app: php-crud
    spec:
      containers:
        - name: php-crud 
          image: bresssanvt/php-crud-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: php-crud-config
            - secretRef:
                name: php-crud-secret
          

