# Secret armazena credenciais sens√≠veis em base64.
# Para gerar: echo -n "crud_password" | base64
apiVersion: v1
kind: Secret
metadata:
  name: php-crud-secret
type: Opaque
data:
  DB_PASSWORD: Y3J1ZF9wYXNzd29yZA==         # crud_password
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== # root_password

